# Welcome to Plus!
#
# This config file affects your whole blog.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
title:                  Open Accessibility
description:            Here you can work with the dynamic, interactive and open accessibility planning tool GOAT. This makes it a great instrument for walking and cycling.
url:                    # Site base hostname & protocol, e.g. http://example.com
baseurl:                # Site subpath, e.g. /blog
lang:                   en
logo:                   logo.png
permalink:              /:title/ # Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
date_format:            "%b %-d, %Y" # refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
uploads:                /uploads/ # Path to post content assets directory i.e post images, pdfs etc

# Pagination Settings
pagination:
  enabled: true
  per_page: 9
  permalink: '/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  
navbar:
  color:                dark # text color, dark or light
  sticky:               true
  search:               false

footer:                 
  copyright:            Open Accessibility 2020 | All Rights Reserved
  logos:
    - image:            logo-tum.png
      url:              https://www.bgu.tum.de/sv/startseite/
    - image:            logo-bmvi.png
      url:              https://www.bmvi.de/DE/Home/home.html
    - image:            logo-mfund.png
      url:              https://www.bmvi.de/SharedDocs/DE/Artikel/DG/mfund-projekte/GOAT.html
  
google_analytics:       # Google analytics code, get your code here https://www.google.com/analytics/

disqus:
  shortname:            # Disqus comments shortname, requires Disqus account https://disqus.com/

# Social share buttons
social_share:
  twitter:              true
  facebook:             true
  linkedin:             true
  pinterest:            true
  reddit:               true

# Social buttons
social_networks:
  email:                
  website:
  facebook:             
  flickr:
  dribbble:
  github:               https://github.com/goat-community/goat
  googleplus:
  instagram:            
  linkedin:             https://www.linkedin.com/company/goat-tool/
  pinterest:
  twitter:              https://twitter.com/GoatTool
  vimeo:
  youtube:

# Build settings
markdown:               kramdown
highlighter:            rouge
kramdown:
  toc_levels:           "2"

plugins:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-sitemap

exclude: 
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - config
  - Gemfile
  - Gemfile.lock
  - node_modules
  - log
  - tmp
  - Rakefile
  - package.json
  - CHANGELOG
  - LICENSE
  - README
  - /docs

sass:
  style:                compressed

# collections:
collections:
  docs:
    output:             true
  videos:
    output:             false
  tutorials:
    output:             true

# Defaults
defaults:
  # _posts
  - scope:
      path:                 ""
      type:                 posts
    values:
      layout:               post
      section:              large
      width:                small
      # sidebar: 
      #   right:              blog
      comments:             # true
      share:                true
      related:              true
      # mailchimp:            true
      navbar:
        # transparent:        true
        # transparent_color:  light
      header:
        layout:             center
        background_overlay: "rgba(0, 0, 0, 0.5)"
        color:              light
        header_size:        large
        heading_size:       medium
        parallax:           true
  # _pages
  - scope:
      path:                 ""
      type:                 pages
    values:
      layout:               page
  # _docs
  - scope:
      path:         ""
      type:         docs
    values:
      layout:       doc
  # _tutorials
  - scope:
      path:         ""
      type:         tutorials
    values:
      layout:       tutorial